// Copyright (c) 2016 The Constantin Karataev. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd.
//
// Interface X7. Verifying client's handwritten signature - owner
// of WM Keeper WinPro (Classic).
// This interface is designed for verifying authenticity
// of the handwritten signature in messages, generated by WM Keeper WinPro (Classic) keys. All parameters are passed in Win-1251 encoding.

// https://wiki.wmtransfer.com/projects/webmoney/wiki/Interface_X7

package webmoney

import (
	"encoding/xml"
)

type TestSignRequest struct {
	XMLName xml.Name `xml:"testsign"`
	Wmid    string   `xml:"wmid"`
	Plan    string   `xml:"plan"`
	Sign    string   `xml:"sign"`
}

func (t TestSignRequest) GetSignSource(reqn string) (string, error) {

	return t.Wmid + t.Plan + t.Sign, nil
}

type TestSignResponse struct {
	XMLName xml.Name `xml:"testsign"`
	Res     string   `xml:"res"`
}

func (w *WmClient) TestSign(t TestSignRequest) (TestSignResponse, error) {
	X := W3s{
		Interface: XInterface{Name: "ClassicAuth", Type: "w3s"},
		Request:   t,
		Client:    w,
	}
	result := TestSignResponse{}
	err := X.getResult(&result)
	return result, err
}
